WHITESPACE = _{ " "|"\t" }

config = {SOI ~ NEWLINE* ~ (rule ~ NEWLINE*)* ~ EOI}

rule = {
    "rule" ~ NEWLINE ~
        (section ~ NEWLINE )* ~
    "end"
}

section = {condition_section|action_section|style_section|rule}

condition_section = { 
    "condition" ~ NEWLINE ~
        (condition ~ NEWLINE)* ~
    "end"
}
condition = { property ~ compare_op ~ assign_value }
property = ${ ('a'..'z' | '0'..'9' | "_")+ }

action_section = { 
    "action" ~ NEWLINE ~
        (action ~ NEWLINE)* ~
    "end"
}
action = { stop_action|ignore_action|set_action }
stop_action = { "stop" }
ignore_action = { "ignore" }
set_action = { "set" ~ property ~ assign_value}

style_section = {
    "style" ~ NEWLINE ~
        (style ~ NEWLINE)* ~
    "end"
}

style = {property ~ assign_value}

assign_value = {(!NEWLINE ~ ANY)+}

compare_eq = { "=" }
compare_lt = { "<" } 
compare_le = { "<=" }
compare_gt = { ">" }
compare_ge = { ">=" }
compare_match = { "match" }
compare = { compare_eq|compare_match }
compare_op = { compare_eq | compare_lt | compare_le | compare_gt | compare_ge | compare_match }
