WHITESPACE = _{ " "|"\t" }

config = {SOI ~ NEWLINE* ~ ((rule | group) ~ NEWLINE*)* ~ EOI}

rule = {
    "rule" ~ NEWLINE ~
        (section ~ NEWLINE )* ~
    "end"
}

group = {
    "group" ~ property? ~ NEWLINE ~
    	(group_section ~ NEWLINE )* ~
    "end"
}

group_section = {style_section}

section = {condition_section|action_section|style_section|rule}

condition_section = { 
    "condition" ~ NEWLINE ~
        (condition ~ NEWLINE)* ~
    "end"
}
condition = { property ~ compare_op ~ value }
property = ${ ('a'..'z' | '0'..'9' | "_")+ }

action_section = { 
    "action" ~ NEWLINE ~
        (action ~ NEWLINE)* ~
    "end"
}
action = { stop_action|ignore_action|set_action }
stop_action = { "stop" }
ignore_action = { "ignore" }
set_action = { "set" ~ property ~ value}

style_section = {
    "style" ~ NEWLINE ~
        (style ~ NEWLINE)* ~
    "end"
}

style = {property ~ value}

value = {value_string | value_number | value_color | value_urgency | value_null}
value_string = ${ "\"" ~ value_string_inner ~ "\"" }
value_string_inner = {(!"\"" ~ ( "\\\""| ANY))*}
string_char = {
    !("\"" | "\\") ~ ANY
    | "\\\""
}
value_number = { "-"? ~ '0'..'9'+ }
value_urgency = { "low" | "normal" | "critical" }
value_null = { "null" }
value_color = ${ "#" ~ (('0'..'9' | 'a'..'f' | 'A'..'F'){3}){1,2} }

compare_eq = { "=" }
compare_lt = { "<" } 
compare_le = { "<=" }
compare_gt = { ">" }
compare_ge = { ">=" }
compare_match = { "match" }
compare = { compare_eq|compare_match }
compare_op = { compare_eq | compare_lt | compare_le | compare_gt | compare_ge | compare_match }
