name: Rust

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Build
      working-directory: ./i3_notify_bar
      run: cargo build --verbose
    - name: Run tests
      working-directory: ./i3_notify_bar
      run: cargo test --verbose
